// Dialogue script + language data (F2.1, extended by Addon A).
// One source of truth for all enabled languages. Tier B/C varieties and
// Tier A languages pending G3 native-speaker review live in LANGS with
// enabled:false — promotion is a data change, never a language swap (A3.1).

// Addon A A3/A5 language registry. ISO 639-3 codes throughout (A11.3);
// varieties without ISO codes use documented internal codes.
export const LANGS = [
  // Tier A, voice_first, full UI pack, enabled (pilot + waves 1-4 primaries)
  { code: "mr", name: "मराठी", script: "Devanagari", tier: "A", voice_mode: "voice_first", speech: "mr-IN", enabled: true },
  { code: "hi", name: "हिंदी", script: "Devanagari", tier: "A", voice_mode: "voice_first", speech: "hi-IN", enabled: true },
  { code: "bn", name: "বাংলা", script: "Bengali", tier: "A", voice_mode: "voice_first", speech: "bn-IN", enabled: true },
  { code: "ta", name: "தமிழ்", script: "Tamil", tier: "A", voice_mode: "voice_first", speech: "ta-IN", enabled: true },
  { code: "te", name: "తెలుగు", script: "Telugu", tier: "A", voice_mode: "voice_first", speech: "te-IN", enabled: true },
  { code: "gu", name: "ગુજરાતી", script: "Gujarati", tier: "A", voice_mode: "voice_first", speech: "gu-IN", enabled: true },
  { code: "kn", name: "ಕನ್ನಡ", script: "Kannada", tier: "A", voice_mode: "voice_first", speech: "kn-IN", enabled: true },
  { code: "ml", name: "മലയാളം", script: "Malayalam", tier: "A", voice_mode: "voice_first", speech: "ml-IN", enabled: true },
  { code: "or", name: "ଓଡ଼ିଆ", script: "Odia", tier: "A", voice_mode: "voice_first", speech: "or-IN", enabled: true },
  { code: "pa", name: "ਪੰਜਾਬੀ", script: "Gurmukhi", tier: "A", voice_mode: "voice_first", speech: "pa-IN", enabled: true },
  { code: "as", name: "অসমীয়া", script: "Assamese", tier: "A", voice_mode: "voice_first", speech: "as-IN", enabled: true },
  { code: "ur", name: "اردو", script: "Perso-Arabic", tier: "A", voice_mode: "voice_first", speech: "ur-IN", enabled: true },
  // Tier A, pack pending G3 review — flagged, UI-hidden until enabled
  { code: "mai", name: "मैथिली", script: "Devanagari", tier: "A", voice_mode: "dtmf_first", speech: "mai-IN", enabled: false },
  { code: "sat", name: "ᱥᱟᱱᱛᱟᱲᱤ", script: "Ol Chiki", tier: "A", voice_mode: "dtmf_first", speech: "sat-IN", enabled: false },
  { code: "kok", name: "कोंकणी", script: "Devanagari", tier: "A", voice_mode: "dtmf_first", speech: "kok-IN", enabled: false },
  { code: "doi", name: "डोगरी", script: "Devanagari", tier: "A", voice_mode: "dtmf_first", speech: "doi-IN", enabled: false },
  { code: "kas", name: "کٲشُر", script: "Perso-Arabic", tier: "A", voice_mode: "dtmf_first", speech: "kas-IN", enabled: false },
  { code: "ne", name: "नेपाली", script: "Devanagari", tier: "A", voice_mode: "dtmf_first", speech: "ne-IN", enabled: false },
  { code: "sd", name: "सिन्धी", script: "Devanagari", tier: "A", voice_mode: "dtmf_first", speech: "sd-IN", enabled: false },
  { code: "brx", name: "बड़ो", script: "Devanagari", tier: "A", voice_mode: "dtmf_first", speech: "brx-IN", enabled: false },
  { code: "mni", name: "মৈতৈ", script: "Bengali", tier: "A", voice_mode: "dtmf_first", speech: "mni-IN", enabled: false },
  // Tier B/C varieties (A3.3) — dtmf_first / human_assisted, promoted via data (A9.1)
  { code: "bho", name: "भोजपुरी", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "bho-IN", enabled: false },
  { code: "mag", name: "मगही", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "mag-IN", enabled: false },
  { code: "awa", name: "अवधी", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "awa-IN", enabled: false },
  { code: "brj", name: "ब्रज", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "brj-IN", enabled: false },
  { code: "bns", name: "बुंदेली", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "bns-IN", enabled: false },
  { code: "hne", name: "छत्तीसगढ़ी", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "hne-IN", enabled: false },
  { code: "mwr", name: "मारवाड़ी", script: "Devanagari", tier: "B", voice_mode: "dtmf_first", speech: "mwr-IN", enabled: false },
  { code: "tcy", name: "ತುಳು", script: "Kannada", tier: "B", voice_mode: "dtmf_first", speech: "tcy-IN", enabled: false },
  { code: "kokborok", name: "ককবরক", script: "Bengali", tier: "C", voice_mode: "human_assisted", speech: "kok-IN", enabled: false },
  { code: "toto", name: "Gor-Boli", script: "Devanagari", tier: "C", voice_mode: "human_assisted", speech: "hi-IN", enabled: false },
];

// Languages the interview UI can serve voice-first right now.
export const VOICE_LANGS = LANGS.filter(l => l.enabled && l.voice_mode === "voice_first");

export function langName(code) {
  const l = LANGS.find(x => x.code === code);
  return l ? l.name : code;
}

export function speechTag(code) {
  const l = LANGS.find(x => x.code === code);
  return l ? l.speech : `${code}-IN`;
}

export const D = {
  mr: {
    phone_q: "तुमचा मोबाइल नंबर टाका",
    consent: "तुमची उत्तरे तुमच्यासाठी योग्य प्रशिक्षण शोधण्यात मदत करतात. आम्ही ती सरकारबाहेर कोणालाही देत नाही.",
    consent_btn: "1 — सहमत",
    consent_more: "अधिक माहिती",
    notice: "संपूर्ण सूचना: तुमची उत्तरे फक्त तुमच्यासाठी योग्य प्रशिक्षण शोधण्यासाठी वापरली जातात. तुमचा नंबर आणि उत्तरे एकत्र साठवली जात नाहीत. कोणताही लाभ मिळवण्यापूर्वी आधार तपासणी स्वतंत्रपणे होते. तुम्हाला कधीही आमच्या यादीतून नाव काढण्याचा अधिकार आहे.",
    resume_q: "मागच्या वेळी तुम्ही सांगितले होते. अजून बरोबर आहे का?",
    resume_ok: "बरोबर आहे",
    resume_chg: "काही बदलले आहे",
    said: "तुम्ही म्हणालात:",
    correct: "बरोबर",
    again: "पुन्हा",
    yes: "होय", no: "नाही",
    send: "पाठवा",
    recs_title: "तुमच्यासाठी योग्य कोर्स",
    months: "महिने", level: "लेव्हल",
    no_centre: "जवळचे प्रशिक्षण केंद्र आढळले नाही",
    err: "काहीतरी चुकले. पुन्हा प्रयत्न करा.",
    speak_slow: "स्पष्ट ऐकेना आले — पुन्हा बोला",
    dist: "अंतर", km: "किमी",
    stale: "जुनी माहिती",
    override_note: "हा कोर्स तुमची आवड लक्षात घेऊन दाखवत आहोत — थोडी अतिरिक्त तयारी लागेल.",
    partial_title: "आधीच्या शिफारसी",
    partial_note: "अधिक नेमक्या शिफारसींसाठी उर्वरित प्रश्नांची उत्तरे द्या.",
    continue_call2: "पुढे सुरू ठेवा (कॉल 2)",
    end_session: "आता थांबा",
    contacted: "मी केंद्राशी संपर्क केला",
    thanks: "धन्यवाद!",
    followup_q: "तुम्ही कोर्सला जोडलात का? (30-दिवस तपासणी)",
    followup_yes: "होय, जोडलात",
    followup_no: "नाही",
    followup_deciding: "अजून विचारात",
    followup_thanks: "उत्तरासाठी धन्यवाद.",
    gap_zero: "प्रवेशासाठी सज्ज",
    gap_partial: "थोडी तयारी लागेल",
    gap_major: "आधारभूत अभ्यास आवश्यक",
    dropout_warn: "लक्षात ठेवा: हा कोर्स लांबलचक आहे — सहाय्यकाराशी संपर्क साधा",
    pinned_badge: "जिल्हा कार्यालयाची शिफारस",
    rpl_badge: "RPL — तुमचा अनुभव लक्षात",
    coord: "एसएससी समन्वयक",
    rpl_note: "RSETI शिफारस पाठवली — घरचे काम या व्यवसायाशी जुळते",
    op_mode: "ऑपरेटर मोड (किऑस्क)",
    op_id_q: "प्रमाणित ऑपरेटर आयडी",
    op_not_certified: "ऑपरेटर प्रमाणित नाही — किऑस्क अपरिचित ऑपरेटरसाठी बंद आहे",
    asp_badge: "✨ तुमच्या आवडीशी जुळते",
    assisted_badge: "सहाय्यित सत्र",
    qr_call: "स्कॅन करून कॉल करा",
    priv_1: "टोपणनावीत डेटा", priv_2: "DPDPA-नुसार संमती", priv_3: "PIN नाही",
  },
  hi: {
    phone_q: "अपना मोबाइल नंबर डालें",
    consent: "आपके उत्तर आपके लिए सही प्रशिक्षण खोजने में मदद करते हैं। हम उन्हें सरकार के बाहर किसी को नहीं देते।",
    consent_btn: "1 — सहमत",
    consent_more: "अधिक जानकारी",
    notice: "पूरी सूचना: आपके उत्तर केवल आपके लिए सही प्रशिक्षण खोजने के लिए उपयोग होते हैं। आपका नंबर और उत्तर एक साथ संग्रहीत नहीं होते। कोई भी लाभ पाने से पहले आधार जाँच अलग से होती है। आप कभी भी हमारी सूची से अपना नाम हटवा सकते हैं।",
    resume_q: "पिछली बार आपने यह बताया था। क्या अभी भी सही है?",
    resume_ok: "सही है",
    resume_chg: "कुछ बदल गया है",
    said: "आपने कहा:",
    correct: "सही",
    again: "फिर से",
    yes: "हाँ", no: "नहीं",
    send: "भेजें",
    recs_title: "आपके लिए सही कोर्स",
    months: "महीने", level: "स्तर",
    no_centre: "पास का प्रशिक्षण केंद्र नहीं मिला",
    err: "कुछ गड़बड़ हुई। फिर कोशिश करें।",
    speak_slow: "स्पष्ट नहीं सुना — फिर बोलें",
    dist: "दूरी", km: "किमी",
    stale: "पुरानी जानकारी",
    override_note: "यह कोर्स आपकी रुचि के अनुसार है — थोड़ी अतिरिक्त तैयारी चाहिए।",
    partial_title: "प्रारंभिक सिफारिशें",
    partial_note: "अधिक सटीक सिफारिशों के लिए बाकी सवालों के जवाब दें।",
    continue_call2: "जारी रखें (कॉल 2)",
    end_session: "अब रुकें",
    contacted: "मैं केंद्र से संपर्क किया",
    thanks: "धन्यवाद!",
    followup_q: "क्या आपने कोर्स ज्वाइन किया? (30-दिवस जाँच)",
    followup_yes: "हाँ, ज्वाइन किया",
    followup_no: "नहीं",
    followup_deciding: "अभी सोच रहा हूँ",
    followup_thanks: "जवाब के लिए धन्यवाद।",
    gap_zero: "प्रवेश के लिए तैयार",
    gap_partial: "थोड़ी तैयारी चाहिए",
    gap_major: "आधारभूत अभ्यास आवश्यक",
    dropout_warn: "ध्यान रखें: यह कोर्स लंबा है — सहायक से संपर्क करें",
    pinned_badge: "जिला कार्यालय की सिफारिश",
    rpl_badge: "RPL — आपका अनुभव मान्य",
    coord: "एसएससी समन्वयक",
    rpl_note: "RSETI सिफारिश भेजी गई — घर का काम इस व्यवसाय से मेल खाता है",
    op_mode: "ऑपरेटर मोड (कियोस्क)",
    op_id_q: "प्रमाणित ऑपरेटर आईडी",
    op_not_certified: "ऑपरेटर प्रमाणित नहीं — कियोस्क अप्रमाणित ऑपरेटर के लिए बंद है",
    asp_badge: "✨ आपकी रुचि से मेल खाता है",
    assisted_badge: "सहायक सत्र",
    qr_call: "स्कैन करके कॉल करें",
    priv_1: "छद्मनामित डेटा", priv_2: "DPDPA-अनुरूप सहमति", priv_3: "PIN नहीं",
  },
  bn: {
    phone_q: "আপনার মোবাইল নম্বর দিন",
    consent: "আপনার উত্তর আপনার জন্য সঠিক প্রশিক্ষণ খুঁজতে সাহায্য করে। আমরা এগুলো সরকারের বাইরে কাউকে দিই না।",
    consent_btn: "1 — সহমত",
    consent_more: "আরও তথ্য",
    notice: "সম্পূর্ণ বিজ্ঞপ্তি: আপনার উত্তর শুধু আপনার জন্য সঠিক প্রশিক্ষণ খুঁজতে ব্যবহার হয়। আপনার নম্বর ও উত্তর একসঙ্গে সংরক্ষণ করা হয় না। কোনো সুবিধার আগে আধার যাচাই আলাদাভাবে হয়। আপনি যেকোনো সময় তালিকা থেকে নাম বাদ দিতে পারেন।",
    resume_q: "গতবার আপনি এটাই বলেছিলেন। এখনও কি ঠিক আছে?",
    resume_ok: "ঠিক আছে",
    resume_chg: "কিছু বদলেছে",
    said: "আপনি বললেন:",
    correct: "ঠিক",
    again: "আবার",
    yes: "হ্যাঁ", no: "না",
    send: "পাঠান",
    recs_title: "আপনার জন্য সঠিক কোর্স",
    months: "মাস", level: "স্তর",
    no_centre: "কাছাকাছি প্রশিক্ষণ কেন্দ্র পাওয়া যায়নি",
    err: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
    speak_slow: "স্পষ্ট শোনা যায়নি — আবার বলুন",
    dist: "দূরত্ব", km: "কিমি",
    stale: "পুরনো তথ্য",
    override_note: "এই কোর্সটি আপনার পছন্দ অনুযায়ী দেখানো হচ্ছে — একটু অতিরিক্ত প্রস্তুতি লাগবে।",
    partial_title: "প্রাথমিক সুপারিশ",
    partial_note: "আরও নির্ভুল সুপারিশের জন্য বাকি প্রশ্নের উত্তর দিন।",
    continue_call2: "চালিয়ে যান (কল 2)",
    end_session: "এখন থামুন",
    contacted: "আমি কেন্দ্রের সঙ্গে যোগাযোগ করেছি",
    thanks: "ধন্যবাদ!",
    followup_q: "আপনি কি কোর্সে যোগ দিয়েছেন? (30-দিনের খোঁজ)",
    followup_yes: "হ্যাঁ, যোগ দিয়েছি",
    followup_no: "না",
    followup_deciding: "এখনও ভাবছি",
    followup_thanks: "উত্তরের জন্য ধন্যবাদ।",
    gap_zero: "ভর্তির জন্য প্রস্তুত",
    gap_partial: "একটু প্রস্তুতি লাগবে",
    gap_major: "ভিত্তিমূলক পড়াশোনা দরকার",
    dropout_warn: "মনে রাখবেন: এই কোর্সটি লম্বা — সহায়কের সঙ্গে যোগাযোগ করুন",
    pinned_badge: "জেলা কার্যালয়ের সুপারিশ",
    rpl_badge: "RPL — আপনার অভিজ্ঞতা গণ্য",
    coord: "এসএসসি সমন্বয়কারী",
    rpl_note: "RSETI সুপারিশ পাঠানো হয়েছে — বাড়ির কাজ এই ব্যবসার সঙ্গে মেলে",
    op_mode: "অপারেটর মোড (কিয়স্ক)",
    op_id_q: "প্রত্যয়িত অপারেটর আইডি",
    op_not_certified: "অপারেটর প্রত্যয়িত নয় — কিয়স্ক বন্ধ আছে",
    asp_badge: "✨ আপনার পছন্দের সঙ্গে মিলেছে",
    assisted_badge: "সহায়তাপ্রাপ্ত সেশন",
    qr_call: "স্ক্যান করে কল করুন",
    priv_1: "ছদ্মনামযুক্ত ডেটা", priv_2: "DPDPA-অনুযায়ী সম্মতি", priv_3: "PIN নেই",
  },
  ta: {
    phone_q: "உங்கள் மொபைல் எண்ணை உள்ளிடுங்கள்",
    consent: "உங்கள் பதில்கள் உங்களுக்கு ஏற்ற பயிற்சியைக் கண்டறிய உதவுகின்றன. அரசுக்கு வெளியே யாருக்கும் கொடுக்க மாட்டோம்.",
    consent_btn: "1 — சம்மதம்",
    consent_more: "மேலும் தகவல்",
    notice: "முழு அறிவிப்பு: உங்கள் பதில்கள் உங்களுக்கு ஏற்ற பயிற்சிக்கு மட்டுமே பயன்படும். உங்கள் எண்ணும் பதில்களும் சேர்த்து சேமிக்கப்படாது. எந்தப் பலனுக்கும் முன் ஆதார் சரிபார்ப்பு தனியே நடக்கும். பட்டியலிலிருந்து எப்போதும் விலகலாம்.",
    resume_q: "கடந்த முறை இதைத்தான் சொன்னீர்கள். இன்னும் சரியா?",
    resume_ok: "சரிதான்",
    resume_chg: "கொஞ்சம் மாறிவிட்டது",
    said: "நீங்கள் சொன்னது:",
    correct: "சரி",
    again: "மீண்டும்",
    yes: "ஆம்", no: "இல்லை",
    send: "அனுப்பு",
    recs_title: "உங்களுக்கான சரியான படிப்புகள்",
    months: "மாதங்கள்", level: "நிலை",
    no_centre: "அருகில் பயிற்சி மையம் இல்லை",
    err: "ஏதோ தவறு. மீண்டும் முயலுங்கள்.",
    speak_slow: "தெளிவாகக் கேட்கவில்லை — மீண்டும் சொல்லுங்கள்",
    dist: "தூரம்", km: "கிமீ",
    stale: "பழைய தகவல்",
    override_note: "இந்தப் படிப்பு உங்கள் விருப்பப்படி காட்டப்படுகிறது — கொஞ்சம் கூடுதல் தயாரிப்பு தேவை.",
    partial_title: "தொடக்கப் பரிந்துரைகள்",
    partial_note: "துல்லியமான பரிந்துரைகளுக்கு மீதிக் கேள்விகளுக்கும் பதில் சொல்லுங்கள்.",
    continue_call2: "தொடருங்கள் (அழைப்பு 2)",
    end_session: "இப்போது நிறுத்து",
    contacted: "மையத்தைத் தொடர்பு கொண்டேன்",
    thanks: "நன்றி!",
    followup_q: "படிப்பில் சேர்ந்துவிட்டீர்களா? (30-நாள் விசாரிப்பு)",
    followup_yes: "ஆம், சேர்ந்துவிட்டேன்",
    followup_no: "இல்லை",
    followup_deciding: "இன்னும் யோசிக்கிறேன்",
    followup_thanks: "பதிலுக்கு நன்றி.",
    gap_zero: "சேரத் தயார்",
    gap_partial: "கொஞ்சம் தயாரிப்பு தேவை",
    gap_major: "அடிப்படைப் படிப்பு தேவை",
    dropout_warn: "நினைவில் கொள்க: இது நீண்ட படிப்பு — உதவியாளரைத் தொடர்பு கொள்ளுங்கள்",
    pinned_badge: "மாவட்ட அலுவலகப் பரிந்துரை",
    rpl_badge: "RPL — உங்கள் அனுபவம் கணக்கில்",
    coord: "SSC ஒருங்கிணைப்பாளர்",
    rpl_note: "RSETI பரிந்துரை அனுப்பப்பட்டது — வீட்டுத் தொழில் இந்தத் தொழிலுடன் பொருந்துகிறது",
    op_mode: "இயக்குநர் முறை (கியாஸ்க்)",
    op_id_q: "சான்றளிக்கப்பட்ட இயக்குநர் ID",
    op_not_certified: "இயக்குநர் சான்றளிக்கப்படவில்லை — கியாஸ்க் மூடப்பட்டுள்ளது",
    asp_badge: "✨ உங்கள் விருப்பத்துடன் பொருந்துகிறது",
    assisted_badge: "உதவியுடன் அமர்வு",
    qr_call: "ஸ்கேன் செய்து அழையுங்கள்",
    priv_1: "புனைப்பெயர் தரவு", priv_2: "DPDPA இணக்க ஒப்புதல்", priv_3: "PIN இல்லை",
  },
  te: {
    phone_q: "మీ మొబైల్ నంబర్ ఇవ్వండి",
    consent: "మీ సమాధానాలు మీకు సరైన శిక్షణను కనుగొనడంలో సహాయపడతాయి. వాటిని ప్రభుత్వం బయట ఎవరికీ ఇవ్వము.",
    consent_btn: "1 — అంగీకారం",
    consent_more: "మరింత సమాచారం",
    notice: "పూర్తి ప్రకటన: మీ సమాధానాలు మీకు సరైన శిక్షణ కోసం మాత్రమే వాడతాము. మీ నంబర్, సమాధానాలు కలిపి నిల్వ చేయము. ఏ ప్రయోజనానికైనా ముందు ఆధార్ తనిఖీ విడిగా జరుగుతుంది. మా జాబితా నుండి ఎప్పుడైనా తొలగించుకోవచ్చు.",
    resume_q: "గతసారి మీరు ఇదే చెప్పారు. ఇప్పటికీ సరైనదేనా?",
    resume_ok: "సరైనదే",
    resume_chg: "కొంత మారింది",
    said: "మీరు చెప్పింది:",
    correct: "సరే",
    again: "మళ్లీ",
    yes: "అవును", no: "కాదు",
    send: "పంపు",
    recs_title: "మీకు సరైన కోర్సులు",
    months: "నెలలు", level: "స్థాయి",
    no_centre: "దగ్గర్లో శిక్షణ కేంద్రం లేదు",
    err: "ఏదో తప్పింది. మళ్లీ ప్రయత్నించండి.",
    speak_slow: "స్పష్టంగా వినపడలేదు — మళ్లీ చెప్పండి",
    dist: "దూరం", km: "కిమీ",
    stale: "పాత సమాచారం",
    override_note: "ఈ కోర్సు మీ అభిరుచి ప్రకారం చూపిస్తున్నాము — కొంత అదనపు సన్నద్ధత అవసరం.",
    partial_title: "ప్రాథమిక సిఫార్సులు",
    partial_note: "ఖచ్చితమైన సిఫార్సుల కోసం మిగతా ప్రశ్నలకు సమాధానం ఇవ్వండి.",
    continue_call2: "కొనసాగించండి (కాల్ 2)",
    end_session: "ఇప్పుడు ఆపు",
    contacted: "కేంద్రాన్ని సంప్రదించాను",
    thanks: "ధన్యవాదాలు!",
    followup_q: "కోర్సులో చేరారా? (30-రోజుల విచారణ)",
    followup_yes: "అవును, చేరాను",
    followup_no: "లేదు",
    followup_deciding: "ఇంకా ఆలోచిస్తున్నాను",
    followup_thanks: "సమాధానానికి ధన్యవాదాలు.",
    gap_zero: "చేరడానికి సిద్ధం",
    gap_partial: "కొంత సన్నద్ధత కావాలి",
    gap_major: "ప్రాథమిక చదువు అవసరం",
    dropout_warn: "గుర్తుంచుకోండి: ఇది దీర్ఘ కోర్సు — సహాయకుడిని సంప్రదించండి",
    pinned_badge: "జిల్లా కార్యాలయ సిఫార్సు",
    rpl_badge: "RPL — మీ అనుభవం లెక్కలోకి",
    coord: "SSC సమన్వయకర్త",
    rpl_note: "RSETI రిఫరల్ పంపబడింది — ఇంటి పని ఈ వృత్తికి సరిపోతుంది",
    op_mode: "ఆపరేటర్ మోడ్ (కియోస్క్)",
    op_id_q: "ధృవీకృత ఆపరేటర్ ID",
    op_not_certified: "ఆపరేటర్ ధృవీకరించబడలేదు — కియోస్క్ మూసివేయబడింది",
    asp_badge: "✨ మీ అభిరుచికి సరిపోతుంది",
    assisted_badge: "సహాయక సెషన్",
    qr_call: "స్కాన్ చేసి కాల్ చేయండి",
    priv_1: "మారుపేరు డేటా", priv_2: "DPDPA అనుగుణ సమ్మతి", priv_3: "PIN లేదు",
  },
  gu: {
    phone_q: "તમારો મોબાઇલ નંબર નાખો",
    consent: "તમારા જવાબો તમારા માટે યોગ્ય તાલીમ શોધવામાં મદદ કરે છે. અમે તે સરકાર બહાર કોઈને આપતા નથી.",
    consent_btn: "1 — સંમત",
    consent_more: "વધુ માહિતી",
    notice: "સંપૂર્ણ સૂચના: તમારા જવાબો ફક્ત તમારા માટે યોગ્ય તાલીમ શોધવા વપરાય છે. તમારો નંબર અને જવાબો ભેગા સંગ્રહાતા નથી. કોઈપણ લાભ પહેલા આધાર તપાસ અલગથી થાય છે. તમે ક્યારેય અમારી યાદીમાંથી નામ કઢાવી શકો છો.",
    resume_q: "ગયા વખતે તમે આ જ કહ્યું હતું. હજુ બરાબર છે?",
    resume_ok: "બરાબર છે",
    resume_chg: "કંઈક બદલાયું છે",
    said: "તમે કહ્યું:",
    correct: "બરાબર",
    again: "ફરી",
    yes: "હા", no: "ના",
    send: "મોકલો",
    recs_title: "તમારા માટે યોગ્ય કોર્સ",
    months: "મહિના", level: "સ્તર",
    no_centre: "નજીકમાં તાલીમ કેન્દ્ર મળ્યું નથી",
    err: "કંઈક ખોટું થયું. ફરી પ્રયાસ કરો.",
    speak_slow: "સ્પષ્ટ સંભળાયું નહીં — ફરી બોલો",
    dist: "અંતર", km: "કિમી",
    stale: "જૂની માહિતી",
    override_note: "આ કોર્સ તમારી રુચિ મુજબ બતાવીએ છીએ — થોડી વધારાની તૈયારી જોઈશે.",
    partial_title: "પ્રાથમિક ભલામણો",
    partial_note: "વધુ ચોક્કસ ભલામણો માટે બાકીના પ્રશ્નોના જવાબ આપો.",
    continue_call2: "આગળ વધો (કૉલ 2)",
    end_session: "હવે અટકો",
    contacted: "મેં કેન્દ્રનો સંપર્ક કર્યો",
    thanks: "આભાર!",
    followup_q: "તમે કોર્સમાં જોડાયા? (30-દિવસ તપાસ)",
    followup_yes: "હા, જોડાયો",
    followup_no: "ના",
    followup_deciding: "હજુ વિચારું છું",
    followup_thanks: "જવાબ બદલ આભાર.",
    gap_zero: "પ્રવેશ માટે તૈયાર",
    gap_partial: "થોડી તૈયારી જોઈએ",
    gap_major: "પાયાનો અભ્યાસ જરૂરી",
    dropout_warn: "યાદ રાખો: આ લાંબો કોર્સ છે — સહાયકનો સંપર્ક કરો",
    pinned_badge: "જિલ્લા કચેરીની ભલામણ",
    rpl_badge: "RPL — તમારો અનુભવ ધ્યાને",
    coord: "SSC સંયોજક",
    rpl_note: "RSETI ભલામણ મોકલી — ઘરનું કામ આ વ્યવસાય સાથે બંધબેસે છે",
    op_mode: "ઓપરેટર મોડ (કિઓસ્ક)",
    op_id_q: "પ્રમાણિત ઓપરેટર ID",
    op_not_certified: "ઓપરેટર પ્રમાણિત નથી — કિઓસ્ક બંધ છે",
    asp_badge: "✨ તમારી રુચિ સાથે બંધબેસે છે",
    assisted_badge: "સહાયિત સત્ર",
    qr_call: "સ્કેન કરીને કૉલ કરો",
    priv_1: "ઉપનામ ડેટા", priv_2: "DPDPA-મુજબ સંમતિ", priv_3: "PIN નથી",
  },
  kn: {
    phone_q: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಹಾಕಿ",
    consent: "ನಿಮ್ಮ ಉತ್ತರಗಳು ನಿಮಗೆ ಸೂಕ್ತ ತರಬೇತಿ ಹುಡುಕಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ. ಸರ್ಕಾರದ ಹೊರಗೆ ಯಾರಿಗೂ ಕೊಡುವುದಿಲ್ಲ.",
    consent_btn: "1 — ಒಪ್ಪಿಗೆ",
    consent_more: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ",
    notice: "ಪೂರ್ಣ ಸೂಚನೆ: ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ನಿಮಗೆ ಸೂಕ್ತ ತರಬೇತಿಗಾಗಿ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ. ನಿಮ್ಮ ಸಂಖ್ಯೆ ಮತ್ತು ಉತ್ತರಗಳನ್ನು ಒಟ್ಟಿಗೆ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ. ಯಾವುದೇ ಪ್ರಯೋಜನಕ್ಕೂ ಮುನ್ನ ಆಧಾರ್ ಪರಿಶೀಲನೆ ಪ್ರತ್ಯೇಕವಾಗಿ ನಡೆಯುತ್ತದೆ. ನಮ್ಮ ಪಟ್ಟಿಯಿಂದ ಯಾವಾಗಲೂ ಹೆಸರು ತೆಗೆಯಿಸಬಹುದು.",
    resume_q: "ಹೋದ ಸಲ ನೀವು ಹೀಗೇ ಹೇಳಿದ್ದೀರಿ. ಈಗಲೂ ಸರಿಯೇ?",
    resume_ok: "ಸರಿಯಿದೆ",
    resume_chg: "ಏನೋ ಬದಲಾಗಿದೆ",
    said: "ನೀವು ಹೇಳಿದ್ದು:",
    correct: "ಸರಿ",
    again: "ಮತ್ತೆ",
    yes: "ಹೌದು", no: "ಇಲ್ಲ",
    send: "ಕಳುಹಿಸಿ",
    recs_title: "ನಿಮಗೆ ಸೂಕ್ತ ಕೋರ್ಸ್‌ಗಳು",
    months: "ತಿಂಗಳು", level: "ಹಂತ",
    no_centre: "ಹತ್ತಿರ ತರಬೇತಿ ಕೇಂದ್ರ ಸಿಗಲಿಲ್ಲ",
    err: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    speak_slow: "ಸ್ಪಷ್ಟವಾಗಿ ಕೇಳಿಸಲಿಲ್ಲ — ಮತ್ತೆ ಹೇಳಿ",
    dist: "ದೂರ", km: "ಕಿಮೀ",
    stale: "ಹಳೆಯ ಮಾಹಿತಿ",
    override_note: "ಈ ಕೋರ್ಸ್ ನಿಮ್ಮ ಆಸಕ್ತಿಯಂತೆ ತೋರಿಸುತ್ತಿದ್ದೇವೆ — ಸ್ವಲ್ಪ ಹೆಚ್ಚಿನ ಸಿದ್ಧತೆ ಬೇಕು.",
    partial_title: "ಆರಂಭಿಕ ಶಿಫಾರಸುಗಳು",
    partial_note: "ನಿಖರ ಶಿಫಾರಸುಗಳಿಗಾಗಿ ಉಳಿದ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.",
    continue_call2: "ಮುಂದುವರಿಸಿ (ಕರೆ 2)",
    end_session: "ಈಗ ನಿಲ್ಲಿಸಿ",
    contacted: "ಕೇಂದ್ರವನ್ನು ಸಂಪರ್ಕಿಸಿದೆ",
    thanks: "ಧನ್ಯವಾದ!",
    followup_q: "ಕೋರ್ಸ್‌ಗೆ ಸೇರಿದ್ದೀರಾ? (30-ದಿನಗಳ ವಿಚಾರಣೆ)",
    followup_yes: "ಹೌದು, ಸೇರಿದ್ದೇನೆ",
    followup_no: "ಇಲ್ಲ",
    followup_deciding: "ಇನ್ನೂ ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ",
    followup_thanks: "ಉತ್ತರಕ್ಕೆ ಧನ್ಯವಾದ.",
    gap_zero: "ಸೇರಲು ಸಿದ್ಧ",
    gap_partial: "ಸ್ವಲ್ಪ ಸಿದ್ಧತೆ ಬೇಕು",
    gap_major: "ಮೂಲಭೂತ ಅಧ್ಯಯನ ಅಗತ್ಯ",
    dropout_warn: "ನೆನಪಿರಲಿ: ಇದು ದೀರ್ಘ ಕೋರ್ಸ್ — ಸಹಾಯಕರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    pinned_badge: "ಜಿಲ್ಲಾ ಕಚೇರಿ ಶಿಫಾರಸು",
    rpl_badge: "RPL — ನಿಮ್ಮ ಅನುಭವ ಪರಿಗಣನೆ",
    coord: "SSC ಸಂಯೋಜಕ",
    rpl_note: "RSETI ಶಿಫಾರಸು ಕಳುಹಿಸಲಾಗಿದೆ — ಮನೆ ಕೆಲಸ ಈ ಉದ್ಯಮಕ್ಕೆ ಹೊಂದುತ್ತದೆ",
    op_mode: "ಆಪರೇಟರ್ ಮೋಡ್ (ಕಿಯೋಸ್ಕ್)",
    op_id_q: "ಪ್ರಮಾಣೀಕೃತ ಆಪರೇಟರ್ ID",
    op_not_certified: "ಆಪರೇಟರ್ ಪ್ರಮಾಣೀಕರಿಸಿಲ್ಲ — ಕಿಯೋಸ್ಕ್ ಮುಚ್ಚಿದೆ",
    asp_badge: "✨ ನಿಮ್ಮ ಆಸಕ್ತಿಗೆ ಹೊಂದುತ್ತದೆ",
    assisted_badge: "ನೆರವಿನ ಅವಧಿ",
    qr_call: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಕರೆ ಮಾಡಿ",
    priv_1: "ಗುಪ್ತನಾಮ ಡೇಟಾ", priv_2: "DPDPA-ಅನುಗುಣ ಒಪ್ಪಿಗೆ", priv_3: "PIN ಇಲ್ಲ",
  },
  ml: {
    phone_q: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകൂ",
    consent: "നിങ്ങളുടെ ഉത്തരങ്ങൾ നിങ്ങൾക്ക് അനുയോജ്യമായ പരിശീലനം കണ്ടെത്താൻ സഹായിക്കുന്നു. സർക്കാരിന് പുറത്ത് ആർക്കും നൽകില്ല.",
    consent_btn: "1 — സമ്മതം",
    consent_more: "കൂടുതൽ വിവരം",
    notice: "പൂർണ്ണ അറിയിപ്പ്: നിങ്ങളുടെ ഉത്തരങ്ങൾ നിങ്ങൾക്ക് അനുയോജ്യമായ പരിശീലനത്തിന് മാത്രമേ ഉപയോഗിക്കൂ. നിങ്ങളുടെ നമ്പറും ഉത്തരങ്ങളും ചേർത്ത് സൂക്ഷിക്കില്ല. ഏതൊരു ആനുകൂല്യത്തിനും മുമ്പ് ആധാർ പരിശോധന പ്രത്യേകം നടക്കും. പട്ടികയിൽ നിന്ന് എപ്പോഴും പേര് നീക്കാം.",
    resume_q: "കഴിഞ്ഞ തവണ നിങ്ങൾ ഇതാണ് പറഞ്ഞത്. ഇപ്പോഴും ശരിയാണോ?",
    resume_ok: "ശരിയാണ്",
    resume_chg: "കുറച്ച് മാറിയിട്ടുണ്ട്",
    said: "നിങ്ങൾ പറഞ്ഞത്:",
    correct: "ശരി",
    again: "വീണ്ടും",
    yes: "അതെ", no: "അല്ല",
    send: "അയയ്ക്കൂ",
    recs_title: "നിങ്ങൾക്കുള്ള ശരിയായ കോഴ്സുകൾ",
    months: "മാസം", level: "നില",
    no_centre: "അടുത്ത് പരിശീലന കേന്ദ്രം ഇല്ല",
    err: "എന്തോ തെറ്റി. വീണ്ടും ശ്രമിക്കൂ.",
    speak_slow: "വ്യക്തമായി കേട്ടില്ല — വീണ്ടും പറയൂ",
    dist: "ദൂരം", km: "കിമീ",
    stale: "പഴയ വിവരം",
    override_note: "ഈ കോഴ്സ് നിങ്ങളുടെ താൽപര്യപ്രകാരമാണ് കാണിക്കുന്നത് — കുറച്ച് അധിക തയ്യാറെടുപ്പ് വേണം.",
    partial_title: "പ്രാഥമിക ശുപാർശകൾ",
    partial_note: "കൃത്യമായ ശുപാർശകൾക്ക് ബാക്കി ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകൂ.",
    continue_call2: "തുടരൂ (കോൾ 2)",
    end_session: "ഇപ്പോൾ നിർത്തൂ",
    contacted: "കേന്ദ്രവുമായി ബന്ധപ്പെട്ടു",
    thanks: "നന്ദി!",
    followup_q: "കോഴ്സിൽ ചേർന്നോ? (30-ദിവസ അന്വേഷണം)",
    followup_yes: "അതെ, ചേർന്നു",
    followup_no: "ഇല്ല",
    followup_deciding: "ഇപ്പോഴും ആലോചിക്കുന്നു",
    followup_thanks: "ഉത്തരത്തിന് നന്ദി.",
    gap_zero: "ചേരാൻ തയ്യാർ",
    gap_partial: "കുറച്ച് തയ്യാറെടുപ്പ് വേണം",
    gap_major: "അടിസ്ഥാന പഠനം ആവശ്യം",
    dropout_warn: "ഓർക്കുക: ഇത് ദൈർഘ്യമേറിയ കോഴ്സാണ് — സഹായിയെ ബന്ധപ്പെടൂ",
    pinned_badge: "ജില്ലാ ഓഫീസ് ശുപാർശ",
    rpl_badge: "RPL — നിങ്ങളുടെ പരിചയം കണക്കിൽ",
    coord: "SSC കോഓർഡിനേറ്റർ",
    rpl_note: "RSETI റഫറൽ അയച്ചു — വീട്ടുജോലി ഈ തൊഴിലിനോട് യോജിക്കുന്നു",
    op_mode: "ഓപ്പറേറ്റർ മോഡ് (കിയോസ്ക്)",
    op_id_q: "സര്ട്ടിഫൈഡ് ഓപ്പറേട്ടർ ID",
    op_not_certified: "ഓപ്പറേറ്റർ സർട്ടിഫൈഡ് അല്ല — കിയോസ്ക് അടച്ചിരിക്കുന്നു",
    asp_badge: "✨ നിങ്ങളുടെ താൽപര്യവുമായി ചേരുന്നു",
    assisted_badge: "സഹായത്തോടെയുള്ള സെഷൻ",
    qr_call: "സ്കാൻ ചെയ്ത് വിളിക്കൂ",
    priv_1: "വിളിപ്പേര് വിവരങ്ങള്", priv_2: "DPDPA-അനുസൃത സമ്മതം", priv_3: "PIN ഇല്ല",
  },
  or: {
    phone_q: "ଆପଣଙ୍କ ମୋବାଇଲ ନମ୍ବର ଦିଅନ୍ତୁ",
    consent: "ଆପଣଙ୍କ ଉତ୍ତର ଆପଣଙ୍କ ପାଇଁ ସଠିକ ତାଲିମ ଖୋଜିବାରେ ସାହାଯ୍ୟ କରେ। ଆମେ ଏହାକୁ ସରକାରଙ୍କ ବାହାରେ କାହାକୁ ଦେଉନାହୁଁ।",
    consent_btn: "1 — ସହମତ",
    consent_more: "ଅଧିକ ସୂଚନା",
    notice: "ସମ୍ପୂର୍ଣ୍ଣ ବିଜ୍ଞପ୍ତି: ଆପଣଙ୍କ ଉତ୍ତର କେବଳ ଆପଣଙ୍କ ପାଇଁ ସଠିକ ତାଲିମ ପାଇଁ ବ୍ୟବହୃତ ହୁଏ। ଆପଣଙ୍କ ନମ୍ବର ଓ ଉତ୍ତର ଏକାଠି ରଖାଯାଏ ନାହିଁ। କୌଣସି ଲାଭ ପୂର୍ବରୁ ଆଧାର ଯାଞ୍ଚ ଅଲଗା ହୁଏ। ଆପଣ ଯେକୌଣସି ସମୟରେ ତାଲିକାରୁ ନାମ କାଢିପାରିବେ।",
    resume_q: "ଗତଥର ଆପଣ ଏହା କହିଥିଲେ। ଏବେ ବି ଠିକ ଅଛି କି?",
    resume_ok: "ଠିକ ଅଛି",
    resume_chg: "କିଛି ବଦଳିଛି",
    said: "ଆପଣ କହିଲେ:",
    correct: "ଠିକ",
    again: "ପୁଣି",
    yes: "ହଁ", no: "ନା",
    send: "ପଠାନ୍ତୁ",
    recs_title: "ଆପଣଙ୍କ ପାଇଁ ସଠିକ କୋର୍ସ",
    months: "ମାସ", level: "ସ୍ତର",
    no_centre: "ପାଖରେ ତାଲିମ କେନ୍ଦ୍ର ମିଳିଲା ନାହିଁ",
    err: "କିଛି ଭୁଲ ହେଲା। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    speak_slow: "ସ୍ପଷ୍ଟ ଶୁଭିଲା ନାହିଁ — ପୁଣି କୁହନ୍ତୁ",
    dist: "ଦୂରତା", km: "କିମି",
    stale: "ପୁରୁଣା ସୂଚନା",
    override_note: "ଏହି କୋର୍ସ ଆପଣଙ୍କ ପସନ୍ଦ ଅନୁସାରେ ଦେଖାଉଛୁ — ଟିକେ ଅଧିକ ପ୍ରସ୍ତୁତି ଦରକାର।",
    partial_title: "ପ୍ରାଥମିକ ସୁପାରିସ",
    partial_note: "ଅଧିକ ନିର୍ଭୁଲ ସୁପାରିସ ପାଇଁ ବାକି ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଅନ୍ତୁ।",
    continue_call2: "ଆଗକୁ ବଢନ୍ତୁ (କଲ 2)",
    end_session: "ବର୍ତ୍ତମାନ ଅଟକନ୍ତୁ",
    contacted: "ମୁଁ କେନ୍ଦ୍ର ସହ ଯୋଗାଯୋଗ କଲି",
    thanks: "ଧନ୍ୟବାଦ!",
    followup_q: "ଆପଣ କୋର୍ସରେ ଯୋଗ ଦେଲେ କି? (30-ଦିନ ପଚରା)",
    followup_yes: "ହଁ, ଯୋଗ ଦେଲି",
    followup_no: "ନା",
    followup_deciding: "ଏବେ ବି ଭାବୁଛି",
    followup_thanks: "ଉତ୍ତର ପାଇଁ ଧନ୍ୟବାଦ।",
    gap_zero: "ନାମ ଲେଖାଇବାକୁ ପ୍ରସ୍ତୁତ",
    gap_partial: "ଟିକେ ପ୍ରସ୍ତୁତି ଦରକାର",
    gap_major: "ମୂଳ ପାଠ ଦରକାର",
    dropout_warn: "ମନେରଖନ୍ତୁ: ଏହା ଲମ୍ବା କୋର୍ସ — ସହାୟକଙ୍କୁ ଯୋଗାଯୋଗ କରନ୍ତୁ",
    pinned_badge: "ଜିଲ୍ଲା କାର୍ଯ୍ୟାଳୟ ସୁପାରିସ",
    rpl_badge: "RPL — ଆପଣଙ୍କ ଅନୁଭବ ଗଣନା",
    coord: "SSC ସଂଯୋଜକ",
    rpl_note: "RSETI ସୁପାରିସ ପଠାଗଲା — ଘର କାମ ଏହି ବ୍ୟବସାୟ ସହ ମେଳ ଖାଉଛି",
    op_mode: "ଅପରେଟର ମୋଡ (କିଓସ୍କ)",
    op_id_q: "ପ୍ରମାଣିତ ଅପରେଟର ID",
    op_not_certified: "ଅପରେଟର ପ୍ରମାଣିତ ନୁହେଁ — କିଓସ୍କ ବନ୍ଦ ଅଛି",
    asp_badge: "✨ ଆପଣଙ୍କ ପସନ୍ଦ ସହ ମେଳ ଖାଉଛି",
    assisted_badge: "ସହାୟତାପ୍ରାପ୍ତ ଅଧିବେଶନ",
    qr_call: "ସ୍କାନ କରି କଲ କରନ୍ତୁ",
    priv_1: "ଛଦ୍ମନାମ ଡାଟା", priv_2: "DPDPA-ଅନୁଯାୟୀ ସମ୍ମତି", priv_3: "PIN ନାହିଁ",
  },
  pa: {
    phone_q: "ਆਪਣਾ ਮੋਬਾਇਲ ਨੰਬਰ ਪਾਓ",
    consent: "ਤੁਹਾਡੇ ਜਵਾਬ ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਸਿਖਲਾਈ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰਦੇ ਹਨ। ਅਸੀਂ ਇਹ ਸਰਕਾਰ ਤੋਂ ਬਾਹਰ ਕਿਸੇ ਨੂੰ ਨਹੀਂ ਦਿੰਦੇ।",
    consent_btn: "1 — ਸਹਿਮਤ",
    consent_more: "ਹੋਰ ਜਾਣਕਾਰੀ",
    notice: "ਪੂਰੀ ਸੂਚਨਾ: ਤੁਹਾਡੇ ਜਵਾਬ ਸਿਰਫ਼ ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਸਿਖਲਾਈ ਲਈ ਵਰਤੇ ਜਾਂਦੇ ਹਨ। ਤੁਹਾਡਾ ਨੰਬਰ ਅਤੇ ਜਵਾਬ ਇਕੱਠੇ ਸਟੋਰ ਨਹੀਂ ਹੁੰਦੇ। ਕਿਸੇ ਵੀ ਲਾਭ ਤੋਂ ਪਹਿਲਾਂ ਆਧਾਰ ਜਾਂਚ ਅਲੱਗ ਹੁੰਦੀ ਹੈ। ਤੁਸੀਂ ਕਦੇ ਵੀ ਸੂਚੀ ਵਿੱਚੋਂ ਨਾਂ ਕਢਵਾ ਸਕਦੇ ਹੋ।",
    resume_q: "ਪਿਛਲੀ ਵਾਰ ਤੁਸੀਂ ਇਹੀ ਦੱਸਿਆ ਸੀ। ਕੀ ਹੁਣ ਵੀ ਠੀਕ ਹੈ?",
    resume_ok: "ਠੀਕ ਹੈ",
    resume_chg: "ਕੁਝ ਬਦਲ ਗਿਆ ਹੈ",
    said: "ਤੁਸੀਂ ਕਿਹਾ:",
    correct: "ਸਹੀ",
    again: "ਮੁੜ",
    yes: "ਹਾਂ", no: "ਨਹੀਂ",
    send: "ਭੇਜੋ",
    recs_title: "ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਕੋਰਸ",
    months: "ਮਹੀਨੇ", level: "ਪੱਧਰ",
    no_centre: "ਨੇੜੇ ਸਿਖਲਾਈ ਕੇਂਦਰ ਨਹੀਂ ਮਿਲਿਆ",
    err: "ਕੁਝ ਗਲਤ ਹੋਇਆ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    speak_slow: "ਸਾਫ਼ ਸੁਣਿਆ ਨਹੀਂ — ਮੁੜ ਬੋਲੋ",
    dist: "ਦੂਰੀ", km: "ਕਿਮੀ",
    stale: "ਪੁਰਾਣੀ ਜਾਣਕਾਰੀ",
    override_note: "ਇਹ ਕੋਰਸ ਤੁਹਾਡੀ ਪਸੰਦ ਅਨੁਸਾਰ ਦਿਖਾ ਰਹੇ ਹਾਂ — ਥੋੜ੍ਹੀ ਵਾਧੂ ਤਿਆਰੀ ਚਾਹੀਦੀ ਹੈ।",
    partial_title: "ਸ਼ੁਰੂਆਤੀ ਸਿਫ਼ਾਰਸ਼ਾਂ",
    partial_note: "ਵਧੇਰੇ ਸਹੀ ਸਿਫ਼ਾਰਸ਼ਾਂ ਲਈ ਬਾਕੀ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ।",
    continue_call2: "ਜਾਰੀ ਰੱਖੋ (ਕਾਲ 2)",
    end_session: "ਹੁਣ ਰੁਕੋ",
    contacted: "ਮੈਂ ਕੇਂਦਰ ਨਾਲ ਸੰਪਰਕ ਕੀਤਾ",
    thanks: "ਧੰਨਵਾਦ!",
    followup_q: "ਕੀ ਤੁਸੀਂ ਕੋਰਸ ਜੁਆਇਨ ਕੀਤਾ? (30-ਦਿਨ ਜਾਂਚ)",
    followup_yes: "ਹਾਂ, ਜੁਆਇਨ ਕੀਤਾ",
    followup_no: "ਨਹੀਂ",
    followup_deciding: "ਹਾਲੇ ਸੋਚ ਰਿਹਾ ਹਾਂ",
    followup_thanks: "ਜਵਾਬ ਲਈ ਧੰਨਵਾਦ।",
    gap_zero: "ਦਾਖ਼ਲੇ ਲਈ ਤਿਆਰ",
    gap_partial: "ਥੋੜ੍ਹੀ ਤਿਆਰੀ ਚਾਹੀਦੀ",
    gap_major: "ਮੁੱਢਲੀ ਪੜ੍ਹਾਈ ਲੋੜੀਂਦੀ",
    dropout_warn: "ਯਾਦ ਰੱਖੋ: ਇਹ ਲੰਬਾ ਕੋਰਸ ਹੈ — ਸਹਾਇਕ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    pinned_badge: "ਜ਼ਿਲ੍ਹਾ ਦਫ਼ਤਰ ਦੀ ਸਿਫ਼ਾਰਸ਼",
    rpl_badge: "RPL — ਤੁਹਾਡਾ ਤਜਰਬਾ ਮੰਨਿਆ",
    coord: "SSC ਤਾਲਮੇਲਕ",
    rpl_note: "RSETI ਸਿਫਾਰਿਸ਼ ਭੇਜੀ ਗਈ — ਘਰ ਦਾ ਕੰਮ ਇਸ ਕਾਰੋਬਾਰ ਨਾਲ ਮਿਲਦਾ ਹੈ",
    op_mode: "ਆਪਰੇਟਰ ਮੋਡ (ਕਿਓਸਕ)",
    op_id_q: "ਪ੍ਰਮਾਣਿਤ ਆਪਰੇਟਰ ID",
    op_not_certified: "ਆਪਰੇਟਰ ਪ੍ਰਮਾਣਿਤ ਨਹੀਂ — ਕਿਓਸਕ ਬੰਦ ਹੈ",
    asp_badge: "✨ ਤੁਹਾਡੀ ਪਸੰਦ ਨਾਲ ਮੇਲ ਖਾਂਦਾ",
    assisted_badge: "ਸਹਾਇਤਾ ਸੈਸ਼ਨ",
    qr_call: "ਸਕੈਨ ਕਰਕੇ ਕਾਲ ਕਰੋ",
    priv_1: "ਛਦਮ ਨਾਮ ਡਾਟਾ", priv_2: "DPDPA-ਅਨੁਕੂਲ ਸਹਿਮਤੀ", priv_3: "PIN ਨਹੀਂ",
  },
  as: {
    phone_q: "আপোনাৰ ম'বাইল নম্বৰ দিয়ক",
    consent: "আপোনাৰ উত্তৰে আপোনাৰ বাবে সঠিক প্ৰশিক্ষণ বিচাৰিবলৈ সহায় কৰে। আমি সেইবোৰ চৰকাৰৰ বাহিৰত কাকো নিদিওঁ।",
    consent_btn: "1 — সন্মত",
    consent_more: "অধিক তথ্য",
    notice: "সম্পূৰ্ণ জাননী: আপোনাৰ উত্তৰ কেৱল আপোনাৰ বাবে সঠিক প্ৰশিক্ষণৰ বাবেহে ব্যৱহাৰ হয়। আপোনাৰ নম্বৰ আৰু উত্তৰ একেলগে ৰখা নহয়। যিকোনো সুবিধাৰ আগতে আধাৰ পৰীক্ষা বেলেগে হয়। আপুনি যিকোনো সময় তালিকাৰ পৰা নাম আঁতৰাব পাৰে।",
    resume_q: "যোৱাবাৰ আপুনি এইটোৱেই কৈছিল। এতিয়াও ঠিকনে?",
    resume_ok: "ঠিক আছে",
    resume_chg: "কিবা সলনি হৈছে",
    said: "আপুনি ক'লে:",
    correct: "শুদ্ধ",
    again: "আকৌ",
    yes: "হয়", no: "নহয়",
    send: "পঠাওক",
    recs_title: "আপোনাৰ বাবে সঠিক কোৰ্চ",
    months: "মাহ", level: "স্তৰ",
    no_centre: "ওচৰত প্ৰশিক্ষণ কেন্দ্ৰ পোৱা নগ'ল",
    err: "কিবা ভুল হ'ল। আকৌ চেষ্টা কৰক।",
    speak_slow: "স্পষ্টকৈ শুনা নগ'ল — আকৌ কওক",
    dist: "দূৰত্ব", km: "কিমি",
    stale: "পুৰণি তথ্য",
    override_note: "এই কোৰ্চটো আপোনাৰ ৰুচি অনুসৰি দেখুৱাইছোঁ — অলপ অতিৰিক্ত সাজু হ'ব লাগিব।",
    partial_title: "প্ৰাৰম্ভিক পৰামৰ্শ",
    partial_note: "অধিক নিখুঁত পৰামৰ্শৰ বাবে বাকী প্ৰশ্নৰ উত্তৰ দিয়ক।",
    continue_call2: "আগবাঢ়ক (কল 2)",
    end_session: "এতিয়া ৰওক",
    contacted: "মই কেন্দ্ৰৰ সৈতে যোগাযোগ কৰিলোঁ",
    thanks: "ধন্যবাদ!",
    followup_q: "আপুনি কোৰ্চত যোগ দিলেনে? (30-দিনীয়া খবৰ)",
    followup_yes: "হয়, যোগ দিলোঁ",
    followup_no: "নহয়",
    followup_deciding: "এতিয়াও ভাবি আছোঁ",
    followup_thanks: "উত্তৰৰ বাবে ধন্যবাদ।",
    gap_zero: "নামভৰ্তিৰ বাবে সাজু",
    gap_partial: "অলপ সাজু হ'ব লাগিব",
    gap_major: "মূল পঢ়া দৰকাৰ",
    dropout_warn: "মনত ৰাখক: এইটো দীঘলীয়া কোৰ্চ — সহায়কৰ সৈতে যোগাযোগ কৰক",
    pinned_badge: "জিলা কাৰ্যালয়ৰ পৰামৰ্শ",
    rpl_badge: "RPL — আপোনাৰ অভিজ্ঞতা গণ্য",
    coord: "SSC সমন্বয়ক",
    rpl_note: "RSETI পৰামৰ্শ পঠিওৱা হ’ল — ঘৰৰ কাম এই ব্যৱসায়ৰ সৈতে মিলে",
    op_mode: "অপাৰেটৰ ম'ড (কিয়'স্ক)",
    op_id_q: "প্ৰমাণিত অপাৰেটৰ ID",
    op_not_certified: "অপাৰেটৰ প্ৰমাণিত নহয় — কিয়'স্ক বন্ধ আছে",
    asp_badge: "✨ আপোনাৰ ৰুচিৰ সৈতে মিলিছে",
    assisted_badge: "সহায়ক অধিবেশন",
    qr_call: "স্কেন কৰি কল কৰক",
    priv_1: "ছদ্মনাম ডাটা", priv_2: "DPDPA-অনুযায়ী সন্মতি", priv_3: "PIN নাই",
  },
  ur: {
    phone_q: "اپنا موبائل نمبر ڈالیں",
    consent: "آپ کے جوابات آپ کے لیے صحیح تربیت تلاش کرنے میں مدد کرتے ہیں۔ ہم انہیں حکومت کے باہر کسی کو نہیں دیتے۔",
    consent_btn: "1 — رضامند",
    consent_more: "مزید معلومات",
    notice: "مکمل اطلاع: آپ کے جوابات صرف آپ کے لیے صحیح تربیت کے لیے استعمال ہوتے ہیں۔ آپ کا نمبر اور جوابات ایک ساتھ محفوظ نہیں ہوتے۔ کسی بھی فائدے سے پہلے آدھار جانچ الگ سے ہوتی ہے۔ آپ کبھی بھی فہرست سے اپنا نام ہٹوا سکتے ہیں۔",
    resume_q: "پچھلی بار آپ نے یہی بتایا تھا۔ کیا اب بھی درست ہے؟",
    resume_ok: "درست ہے",
    resume_chg: "کچھ بدل گیا ہے",
    said: "آپ نے کہا:",
    correct: "صحیح",
    again: "دوبارہ",
    yes: "ہاں", no: "نہیں",
    send: "بھیجیں",
    recs_title: "آپ کے لیے صحیح کورس",
    months: "مہینے", level: "درجہ",
    no_centre: "قریب میں تربیتی مرکز نہیں ملا",
    err: "کچھ گڑبڑ ہوئی۔ پھر کوشش کریں۔",
    speak_slow: "صاف سنائی نہیں دیا — دوبارہ بولیں",
    dist: "فاصلہ", km: "کلومیٹر",
    stale: "پرانی معلومات",
    override_note: "یہ کورس آپ کی دلچسپی کے مطابق دکھا رہے ہیں — تھوڑی اضافی تیاری چاہیے۔",
    partial_title: "ابتدائی سفارشات",
    partial_note: "زیادہ درست سفارشات کے لیے باقی سوالوں کے جواب دیں۔",
    continue_call2: "جاری رکھیں (کال 2)",
    end_session: "اب رکیں",
    contacted: "میں نے مرکز سے رابطہ کیا",
    thanks: "شکریہ!",
    followup_q: "کیا آپ نے کورس جوائن کیا؟ (30-روزہ جانچ)",
    followup_yes: "ہاں، جوائن کیا",
    followup_no: "نہیں",
    followup_deciding: "ابھی سوچ رہا ہوں",
    followup_thanks: "جواب کے لیے شکریہ۔",
    gap_zero: "داخلے کے لیے تیار",
    gap_partial: "تھوڑی تیاری چاہیے",
    gap_major: "بنیادی پڑھائی ضروری",
    dropout_warn: "یاد رکھیں: یہ لمبا کورس ہے — مددگار سے رابطہ کریں",
    pinned_badge: "ضلعی دفتر کی سفارش",
    rpl_badge: "RPL — آپ کا تجربہ منظور",
    coord: "ایس ایس سی رابطہ کار",
    rpl_note: "RSETI سفارش بھیجی گئی — گھر کا کام اس کاروبار سے میل کھاتا ہے",
    op_mode: "آپریٹر موڈ (کیوسک)",
    op_id_q: "تصدیق شدہ آپریٹر ID",
    op_not_certified: "آپریٹر تصدیق شدہ نہیں — کیوسک بند ہے",
    asp_badge: "✨ آپ کی دلچسپی سے میل کھاتا ہے",
    assisted_badge: "امدادی سیشن",
    qr_call: "اسکین کر کے کال کریں",
    priv_1: "فرضی نام ڈیٹا", priv_2: "DPDPA-مطابق رضامندی", priv_3: "PIN نہیں",
  },
};

export const DATA = {
  mr: {
    phone_btn: "पुढे जा",
    phone_err: "10 अंकी नंबर टाका",
    edu: [[0, "कधी शिकले नाही"], [5, "5वी"], [8, "8वी"], [10, "10वी"], [12, "12वी"], [15, "पदवी"]],
    pref: [["self_employment", "स्वतःचा व्यवसाय"], ["wage", "नोकरी"]],
    interest_chips: [["tailoring", "शिवणकाम"], ["farming", "शेती"], ["carpentry", "सुतारकाम"], ["beauty", "सौंदर्य"], ["mobile repair", "मोबाइल दुरुस्ती"], ["shop", "दुकान"]],
    family_chips: [["agricultural labour", "शेतमजूरी"], ["farming", "शेती"], ["carpentry", "सुतारकाम"], ["pottery", "कुंभारकाम"], ["leatherwork", "चांभारकाम"], ["tailoring", "शिंपीकाम"]],
    slot_label: { district_name: "जिल्हा", education_grade: "शिक्षण", primary_interest: "आवड", mobility_constraint: "अडचण", preference: "व्यवसाय/नोकरी", family_occupation: "घरचे काम", nearest_market: "जवळचे बाजार", language: "भाषा" },
  },
  hi: {
    phone_btn: "आगे बढ़ें",
    phone_err: "10 अंकों का नंबर डालें",
    edu: [[0, "कभी नहीं पढ़ा"], [5, "5वीं"], [8, "8वीं"], [10, "10वीं"], [12, "12वीं"], [15, "स्नातक"]],
    pref: [["self_employment", "अपना व्यवसाय"], ["wage", "नौकरी"]],
    interest_chips: [["tailoring", "सिलाई"], ["farming", "खेती"], ["carpentry", "बढ़ई"], ["beauty", "ब्यूटी"], ["mobile repair", "मोबाइल दुरुस्ती"], ["shop", "दुकानदारी"]],
    family_chips: [["agricultural labour", "कृषि मजदूरी"], ["farming", "खेती"], ["carpentry", "बढ़ई"], ["pottery", "कुम्हार"], ["leatherwork", "चर्मकार"], ["tailoring", "दर्जी"]],
    slot_label: { district_name: "जिला", education_grade: "शिक्षा", primary_interest: "रुचि", mobility_constraint: "दिक्कत", preference: "व्यवसाय/नौकरी", family_occupation: "घर का काम", nearest_market: "पास का बाज़ार", language: "भाषा" },
  },
  bn: {
    phone_btn: "এগিয়ে যান",
    phone_err: "10 সংখ্যার নম্বর দিন",
    edu: [[0, "কখনও পড়িনি"], [5, "5ম"], [8, "8ম"], [10, "10ম"], [12, "12শ"], [15, "স্নাতক"]],
    pref: [["self_employment", "নিজের ব্যবসা"], ["wage", "চাকরি"]],
    interest_chips: [["tailoring", "সেলাই"], ["farming", "চাষ"], ["carpentry", "ছুতোর"], ["beauty", "বিউটি"], ["mobile repair", "মোবাইল মেরামত"], ["shop", "দোকান"]],
    family_chips: [["agricultural labour", "খেতমজুর"], ["farming", "চাষ"], ["carpentry", "ছুতোর"], ["pottery", "কুমোর"], ["leatherwork", "চামার"], ["tailoring", "দর্জি"]],
    slot_label: { district_name: "জেলা", education_grade: "শিক্ষা", primary_interest: "পছন্দ", mobility_constraint: "অসুবিধা", preference: "ব্যবসা/চাকরি", family_occupation: "বাড়ির কাজ", nearest_market: "কাছের বাজার", language: "ভাষা" },
  },
  ta: {
    phone_btn: "தொடர்க",
    phone_err: "10 இலக்க எண்ணை உள்ளிடுக",
    edu: [[0, "படிக்கவே இல்லை"], [5, "5ஆம்"], [8, "8ஆம்"], [10, "10ஆம்"], [12, "12ஆம்"], [15, "பட்டம்"]],
    pref: [["self_employment", "சொந்தத் தொழில்"], ["wage", "வேலை"]],
    interest_chips: [["tailoring", "தையல்"], ["farming", "விவசாயம்"], ["carpentry", "தச்சு"], ["beauty", "அழகு"], ["mobile repair", "மொபைல் பழுது"], ["shop", "கடை"]],
    family_chips: [["agricultural labour", "விவசாயக் கூலி"], ["farming", "விவசாயம்"], ["carpentry", "தச்சு"], ["pottery", "குயவு"], ["leatherwork", "தோல்"], ["tailoring", "தையல்"]],
    slot_label: { district_name: "மாவட்டம்", education_grade: "கல்வி", primary_interest: "விருப்பம்", mobility_constraint: "சிரமம்", preference: "தொழில்/வேலை", family_occupation: "வீட்டுத் தொழில்", nearest_market: "அருகுச் சந்தை", language: "மொழி" },
  },
  te: {
    phone_btn: "ముందుకు",
    phone_err: "10 అంకెల నంబర్ ఇవ్వండి",
    edu: [[0, "ఎప్పుడూ చదవలేదు"], [5, "5వ"], [8, "8వ"], [10, "10వ"], [12, "12వ"], [15, "డిగ్రీ"]],
    pref: [["self_employment", "సొంత వ్యాపారం"], ["wage", "ఉద్యోగం"]],
    interest_chips: [["tailoring", "కుట్టు"], ["farming", "వ్యవసాయం"], ["carpentry", "వడ్రంగం"], ["beauty", "బ్యూటీ"], ["mobile repair", "మొబైల్ రిపేరు"], ["shop", "కొట్టు"]],
    family_chips: [["agricultural labour", "వ్యవసాయ కూలీ"], ["farming", "వ్యవసాయం"], ["carpentry", "వడ్రంగం"], ["pottery", "కుమ్మరి"], ["leatherwork", "చర్మకళ"], ["tailoring", "దర్జీ"]],
    slot_label: { district_name: "జిల్లా", education_grade: "విద్య", primary_interest: "అభిరుచి", mobility_constraint: "ఇబ్బంది", preference: "వ్యాపారం/ఉద్యోగం", family_occupation: "ఇంటి పని", nearest_market: "దగ్గరి మార్కెట్", language: "భాష" },
  },
  gu: {
    phone_btn: "આગળ વધો",
    phone_err: "10 અંકનો નંબર નાખો",
    edu: [[0, "ક્યારેય ભણ્યા નથી"], [5, "5મું"], [8, "8મું"], [10, "10મું"], [12, "12મું"], [15, "પદવી"]],
    pref: [["self_employment", "પોતાનો ધંધો"], ["wage", "નોકરી"]],
    interest_chips: [["tailoring", "સીવણ"], ["farming", "ખેતી"], ["carpentry", "સુથારી"], ["beauty", "બ્યુટી"], ["mobile repair", "મોબાઇલ રિપેરિંગ"], ["shop", "દુકાન"]],
    family_chips: [["agricultural labour", "ખેતમજૂરી"], ["farming", "ખેતી"], ["carpentry", "સુથારી"], ["pottery", "કુંભાર"], ["leatherwork", "ચર્મકામ"], ["tailoring", "દરજી"]],
    slot_label: { district_name: "જિલ્લો", education_grade: "શિક્ષણ", primary_interest: "રુચિ", mobility_constraint: "તકલીફ", preference: "ધંધો/નોકરી", family_occupation: "ઘરનું કામ", nearest_market: "નજીકનું બજાર", language: "ભાષા" },
  },
  kn: {
    phone_btn: "ಮುಂದೆ",
    phone_err: "10 ಅಂಕಿಯ ಸಂಖ್ಯೆ ಹಾಕಿ",
    edu: [[0, "ಎಂದೂ ಓದಿಲ್ಲ"], [5, "5ನೇ"], [8, "8ನೇ"], [10, "10ನೇ"], [12, "12ನೇ"], [15, "ಪದವಿ"]],
    pref: [["self_employment", "ಸ್ವಂತ ಉದ್ಯಮ"], ["wage", "ಉದ್ಯೋಗ"]],
    interest_chips: [["tailoring", "ಹೊಲಿಗೆ"], ["farming", "ಕೃಷಿ"], ["carpentry", "ಬಡಗಿ"], ["beauty", "ಬ್ಯೂಟಿ"], ["mobile repair", "ಮೊಬೈಲ್ ದುರಸ್ತಿ"], ["shop", "ಅಂಗಡಿ"]],
    family_chips: [["agricultural labour", "ಕೃಷಿ ಕೂಲಿ"], ["farming", "ಕೃಷಿ"], ["carpentry", "ಬಡಗಿ"], ["pottery", "ಕುಂಬಾರಿಕೆ"], ["leatherwork", "ಚರ್ಮಕಲೆ"], ["tailoring", "ದರ್ಜಿ"]],
    slot_label: { district_name: "ಜಿಲ್ಲೆ", education_grade: "ಶಿಕ್ಷಣ", primary_interest: "ಆಸಕ್ತಿ", mobility_constraint: "ತೊಂದರೆ", preference: "ಉದ್ಯಮ/ಉದ್ಯೋಗ", family_occupation: "ಮನೆ ಕೆಲಸ", nearest_market: "ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆ", language: "ಭಾಷೆ" },
  },
  ml: {
    phone_btn: "മുന്നോട്ട്",
    phone_err: "10 അക്ക നമ്പർ നൽകൂ",
    edu: [[0, "ഒരിക്കലും പഠിച്ചിട്ടില്ല"], [5, "5-ാം"], [8, "8-ാം"], [10, "10-ാം"], [12, "12-ാം"], [15, "ബിരുദം"]],
    pref: [["self_employment", "സ്വന്തം ബിസിനസ്"], ["wage", "ജോലി"]],
    interest_chips: [["tailoring", "തയ്യൽ"], ["farming", "കൃഷി"], ["carpentry", "ആശാരി"], ["beauty", "ബ്യൂട്ടി"], ["mobile repair", "മൊബൈൽ റിപ്പയർ"], ["shop", "കട"]],
    family_chips: [["agricultural labour", "കൃഷിക്കൂലി"], ["farming", "കൃഷി"], ["carpentry", "ആശാരി"], ["pottery", "കുശവൻ"], ["leatherwork", "തുകൽ"], ["tailoring", "തയ്യൽക്കാരൻ"]],
    slot_label: { district_name: "ജില്ല", education_grade: "വിദ്യാഭ്യാസം", primary_interest: "താൽപര്യം", mobility_constraint: "ബുദ്ധിമുട്ട്", preference: "ബിസിനസ്/ജോലി", family_occupation: "വീട്ടുജോലി", nearest_market: "അടുത്ത മാർക്കറ്റ്", language: "ഭാഷ" },
  },
  or: {
    phone_btn: "ଆଗକୁ ବଢନ୍ତୁ",
    phone_err: "10 ଅଙ୍କ ନମ୍ବର ଦିଅନ୍ତୁ",
    edu: [[0, "କେବେ ପଢିନାହିଁ"], [5, "5ମ"], [8, "8ମ"], [10, "10ମ"], [12, "12ଶ"], [15, "ସ୍ନାତକ"]],
    pref: [["self_employment", "ନିଜ ବ୍ୟବସାୟ"], ["wage", "ଚାକିରି"]],
    interest_chips: [["tailoring", "ସିଲାଇ"], ["farming", "ଚାଷ"], ["carpentry", "ବଢେଇ"], ["beauty", "ବ୍ୟୁଟି"], ["mobile repair", "ମୋବାଇଲ ମରାମତି"], ["shop", "ଦୋକାନ"]],
    family_chips: [["agricultural labour", "କୃଷି ମଜୁରି"], ["farming", "ଚାଷ"], ["carpentry", "ବଢେଇ"], ["pottery", "କୁମ୍ଭାର"], ["leatherwork", "ଚମଡା କାମ"], ["tailoring", "ଦରଜି"]],
    slot_label: { district_name: "ଜିଲ୍ଲା", education_grade: "ଶିକ୍ଷା", primary_interest: "ପସନ୍ଦ", mobility_constraint: "ଅସୁବିଧା", preference: "ବ୍ୟବସାୟ/ଚାକିରି", family_occupation: "ଘର କାମ", nearest_market: "ପାଖ ବଜାର", language: "ଭାଷା" },
  },
  pa: {
    phone_btn: "ਅੱਗੇ ਵਧੋ",
    phone_err: "10 ਅੰਕਾਂ ਦਾ ਨੰਬਰ ਪਾਓ",
    edu: [[0, "ਕਦੇ ਪੜ੍ਹਿਆ ਨਹੀਂ"], [5, "5ਵੀਂ"], [8, "8ਵੀਂ"], [10, "10ਵੀਂ"], [12, "12ਵੀਂ"], [15, "ਗ੍ਰੈਜੂਏਟ"]],
    pref: [["self_employment", "ਆਪਣਾ ਕਾਰੋਬਾਰ"], ["wage", "ਨੌਕਰੀ"]],
    interest_chips: [["tailoring", "ਸਿਲਾਈ"], ["farming", "ਖੇਤੀ"], ["carpentry", "ਤਰਖਾਣ"], ["beauty", "ਬਿਊਟੀ"], ["mobile repair", "ਮੋਬਾਇਲ ਮੁਰੰਮਤ"], ["shop", "ਦੁਕਾਨ"]],
    family_chips: [["agricultural labour", "ਖੇਤ ਮਜ਼ਦੂਰੀ"], ["farming", "ਖੇਤੀ"], ["carpentry", "ਤਰਖਾਣ"], ["pottery", "ਘੁਮਿਆਰ"], ["leatherwork", "ਚਮੜਾ ਕੰਮ"], ["tailoring", "ਦਰਜ਼ੀ"]],
    slot_label: { district_name: "ਜ਼ਿਲ੍ਹਾ", education_grade: "ਸਿੱਖਿਆ", primary_interest: "ਪਸੰਦ", mobility_constraint: "ਦਿੱਕਤ", preference: "ਕਾਰੋਬਾਰ/ਨੌਕਰੀ", family_occupation: "ਘਰ ਦਾ ਕੰਮ", nearest_market: "ਨੇੜਲਾ ਬਾਜ਼ਾਰ", language: "ਭਾਸ਼ਾ" },
  },
  as: {
    phone_btn: "আগবাঢ়ক",
    phone_err: "10টা সংখ্যাৰ নম্বৰ দিয়ক",
    edu: [[0, "কেতিয়াও পঢ়া নাই"], [5, "5ম"], [8, "8ম"], [10, "10ম"], [12, "12শ"], [15, "স্নাতক"]],
    pref: [["self_employment", "নিজৰ ব্যৱসায়"], ["wage", "চাকৰি"]],
    interest_chips: [["tailoring", "চিলাই"], ["farming", "খেতি"], ["carpentry", "কাঠমিস্ত্ৰী"], ["beauty", "বিউটি"], ["mobile repair", "ম'বাইল মেৰামতি"], ["shop", "দোকান"]],
    family_chips: [["agricultural labour", "খেতি-বনুৱা"], ["farming", "খেতি"], ["carpentry", "কাঠমিস্ত্ৰী"], ["pottery", "কুমাৰ"], ["leatherwork", "ছালৰ কাম"], ["tailoring", "দৰ্জী"]],
    slot_label: { district_name: "জিলা", education_grade: "শিক্ষা", primary_interest: "ৰুচি", mobility_constraint: "অসুবিধা", preference: "ব্যৱসায়/চাকৰি", family_occupation: "ঘৰৰ কাম", nearest_market: "ওচৰৰ বজাৰ", language: "ভাষা" },
  },
  ur: {
    phone_btn: "آگے بڑھیں",
    phone_err: "10 ہندسوں کا نمبر ڈالیں",
    edu: [[0, "کبھی پڑھا نہیں"], [5, "5ویں"], [8, "8ویں"], [10, "10ویں"], [12, "12ویں"], [15, "گریجویٹ"]],
    pref: [["self_employment", "اپنا کاروبار"], ["wage", "نوکری"]],
    interest_chips: [["tailoring", "سلائی"], ["farming", "کھیتی"], ["carpentry", "بڑھئی"], ["beauty", "بیوٹی"], ["mobile repair", "موبائل مرمت"], ["shop", "دکان"]],
    family_chips: [["agricultural labour", "زرعی مزدوری"], ["farming", "کھیتی"], ["carpentry", "بڑھئی"], ["pottery", "کمہار"], ["leatherwork", "چمڑے کا کام"], ["tailoring", "درزی"]],
    slot_label: { district_name: "ضلع", education_grade: "تعلیم", primary_interest: "دلچسپی", mobility_constraint: "دقت", preference: "کاروبار/نوکری", family_occupation: "گھر کا کام", nearest_market: "قریبی بازار", language: "زبان" },
  },
};

// LGD codes mirror backend/seed.py DISTRICTS. ponytail: unverified except Pune 523.
export const DISTRICTS = [["Pune", "523"], ["Mumbai Suburban", "520"], ["Nashik", "527"], ["Nagpur", "528"], ["Solapur", "534"], ["Kolhapur", "530"], ["Chhatrapati Sambhajinagar", "516"], ["Amravati", "514"], ["Satara", "531"], ["Ahmednagar", "515"]];

// 8 slots in two calls (H2): Call 1 = district, education, interest (partial recs);
// Call 2 = mobility, preference, family occupation, market.
export const SLOTS = [
  { key: "district_name", type: "choice", call: 1, q: { mr: "तुम्ही कोणत्या जिल्ह्यात राहता?", hi: "आप किस जिले में रहते हैं?", bn: "আপনি কোন জেলায় থাকেন?", ta: "நீங்கள் எந்த மாவட்டத்தில் வசிக்கிறீர்கள்?", te: "మీరు ఏ జిల్లాలో ఉంటున్నారు?", gu: "તમે કયા જિલ્લામાં રહો છો?", kn: "ನೀವು ಯಾವ ಜಿಲ್ಲೆಯಲ್ಲಿ ವಾಸಿಸುತ್ತೀರಿ?", ml: "നിങ്ങൾ ഏത് ജില്ലയിലാണ് താമസിക്കുന്നത്?", or: "ଆପଣ କେଉଁ ଜିଲ୍ଲାରେ ରହୁଛନ୍ତି?", pa: "ਤੁਸੀਂ ਕਿਸ ਜ਼ਿਲ੍ਹੇ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?", as: "আপুনি কোন জিলাত থাকে?", ur: "آپ کس ضلع میں رہتے ہیں؟" } },
  { key: "education_grade", type: "choice", call: 1, q: { mr: "तुम्ही कोणत्या श्रेणीपर्यंत शिकलात?", hi: "आप किस कक्षा तक पढ़े हैं?", bn: "আপনি কোন শ্রেণি পর্যন্ত পড়েছেন?", ta: "எந்த வகுப்பு வரை படித்தீர்கள்?", te: "మీరు ఏ తరగతి వరకు చదివారు?", gu: "તમે કયા ધોરણ સુધી ભણ્યા?", kn: "ಯಾವ ತರಗತಿವರೆಗೆ ಓದಿದ್ದೀರಿ?", ml: "ഏത് ക്ലാസ് വരെ പഠിച്ചു?", or: "ଆପଣ କେଉଁ ଶ୍ରେଣୀ ପର୍ଯ୍ୟନ୍ତ ପଢିଛନ୍ତି?", pa: "ਤੁਸੀਂ ਕਿਸ ਜਮਾਤ ਤੱਕ ਪੜ੍ਹੇ ਹੋ?", as: "আপুনি কোন শ্ৰেণীলৈকে পঢ়িছে?", ur: "آپ کس جماعت تک پڑھے ہیں؟" } },
  { key: "primary_interest", type: "text", call: 1, q: { mr: "तुम्हाला कोणते काम आवडते?", hi: "आपको कौन सा काम पसंद है?", bn: "আপনার কোন কাজ পছন্দ?", ta: "உங்களுக்கு எந்த வேலை பிடிக்கும்?", te: "మీకు ఏ పని ఇష్టం?", gu: "તમને કયું કામ ગમે છે?", kn: "ನಿಮಗೆ ಯಾವ ಕೆಲಸ ಇಷ್ಟ?", ml: "നിങ്ങൾക്ക് ഏത് ജോലിയാണ് ഇഷ്ടം?", or: "ଆପଣଙ୍କୁ କେଉଁ କାମ ପସନ୍ଦ?", pa: "ਤੁਹਾਨੂੰ ਕਿਹੜਾ ਕੰਮ ਪਸੰਦ ਹੈ?", as: "আপোনাৰ কোন কাম ভাল লাগে?", ur: "آپ کو کون سا کام پسند ہے؟" } },
  { key: "mobility_constraint", type: "yesno", call: 2, q: { mr: "तुम्हाला चालण्यात किंवा काम करण्यात अडचण आहे का?", hi: "आपको चलने या काम करने में दिक्कत है?", bn: "আপনার হাঁটতে বা কাজ করতে অসুবিধা হয় কি?", ta: "நடக்க அல்லது வேலை செய்யச் சிரமம் உண்டா?", te: "నడవడంలో లేదా పని చేయడంలో ఇబ్బంది ఉందా?", gu: "તમને ચાલવામાં કે કામ કરવામાં તકલીફ છે?", kn: "ನಡೆಯಲು ಅಥವಾ ಕೆಲಸ ಮಾಡಲು ತೊಂದರೆ ಇದೆಯೇ?", ml: "നടക്കാനോ ജോലി ചെയ്യാനോ ബുദ്ധിമുട്ടുണ്ടോ?", or: "ଆପଣଙ୍କୁ ଚାଲିବାରେ କିମ୍ବା କାମ କରିବାରେ ଅସୁବିଧା ଅଛି କି?", pa: "ਕੀ ਤੁਹਾਨੂੰ ਤੁਰਨ ਜਾਂ ਕੰਮ ਕਰਨ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੈ?", as: "আপোনাৰ খোজ কাঢ়িবলৈ বা কাম কৰিবলৈ অসুবিধা হয় নেকি?", ur: "کیا آپ کو چلنے یا کام کرنے میں دقت ہے؟" } },
  { key: "preference", type: "choice", call: 2, q: { mr: "तुम्हाला स्वतःचा व्यवसाय हवा आहे की नोकरी?", hi: "आपको अपना व्यवसाय चाहिए या नौकरी?", bn: "আপনি নিজের ব্যবসা চান নাকি চাকরি?", ta: "சொந்தத் தொழில் வேண்டுமா அல்லது வேலையா?", te: "సొంత వ్యాపారం కావాలా లేక ఉద్యోగమా?", gu: "તમારે પોતાનો ધંધો જોઈએ છે કે નોકરી?", kn: "ಸ್ವಂತ ಉದ್ಯಮ ಬೇಕೇ ಅಥವಾ ಉದ್ಯೋಗವೇ?", ml: "സ്വന്തം ബിസിനസ് വേണോ അതോ ജോലിയോ?", or: "ଆପଣ ନିଜ ବ୍ୟବସାୟ ଚାହାଁନ୍ତି ନା ଚାକିରି?", pa: "ਕੀ ਤੁਹਾਨੂੰ ਆਪਣਾ ਕਾਰੋਬਾਰ ਚਾਹੀਦਾ ਹੈ ਜਾਂ ਨੌਕਰੀ?", as: "আপুনি নিজৰ ব্যৱসায় বিচাৰে নে চাকৰি?", ur: "آپ کو اپنا کاروبار چاہیے یا نوکری؟" } },
  { key: "family_occupation", type: "text", call: 2, q: { mr: "तुमच्या घरात पारंपरिकरित्या कोणते काम चालते?", hi: "आपके घर में पारंपरिक रूप से कौन सा काम चलता है?", bn: "আপনার বাড়িতে ঐতিহ্যগতভাবে কোন কাজ হয়?", ta: "உங்கள் வீட்டில் பரம்பரையாக என்ன தொழில்?", te: "మీ ఇంట్లో సంప్రదాయంగా ఏ పని జరుగుతుంది?", gu: "તમારા ઘરમાં પરંપરાગત રીતે કયું કામ ચાલે છે?", kn: "ನಿಮ್ಮ ಮನೆಯಲ್ಲಿ ಸಾಂಪ್ರದಾಯಿಕವಾಗಿ ಯಾವ ಕೆಲಸ ನಡೆಯುತ್ತದೆ?", ml: "നിങ്ങളുടെ വീട്ടിൽ പരമ്പരാഗതമായി ഏത് ജോലിയാണ് നടക്കുന്നത്?", or: "ଆପଣଙ୍କ ଘରେ ପାରମ୍ପରିକ ଭାବରେ କେଉଁ କାମ ଚାଲେ?", pa: "ਤੁਹਾਡੇ ਘਰ ਵਿੱਚ ਰਵਾਇਤੀ ਤੌਰ 'ਤੇ ਕਿਹੜਾ ਕੰਮ ਹੁੰਦਾ ਹੈ?", as: "আপোনাৰ ঘৰত পৰম্পৰাগতভাৱে কোন কাম চলে?", ur: "آپ کے گھر میں روایتی طور پر کون سا کام ہوتا ہے؟" } },
  { key: "nearest_market", type: "text", call: 2, q: { mr: "तुमच्या जवळचे बाजार किंवा गाव कोणते?", hi: "आपके पास का बाज़ार या कस्बा कौन सा है?", bn: "আপনার কাছের বাজার বা গ্রাম কোনটি?", ta: "உங்கள் அருகுச் சந்தை அல்லது ஊர் எது?", te: "మీ దగ్గరి మార్కెట్ లేదా ఊరు ఏది?", gu: "તમારું નજીકનું બજાર કે ગામ કયું?", kn: "ನಿಮ್ಮ ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆ ಅಥವಾ ಊರು ಯಾವುದು?", ml: "നിങ്ങളുടെ അടുത്ത മാർക്കറ്റ് അല്ലെങ്കിൽ ഗ്രാമം ഏത്?", or: "ଆପଣଙ୍କ ନିକଟ ବଜାର ବା ଗାଁ କେଉଁଟି?", pa: "ਤੁਹਾਡਾ ਨਜ਼ਦੀਕੀ ਬਾਜ਼ਾਰ ਜਾਂ ਪਿੰਡ ਕਿਹੜਾ ਹੈ?", as: "আপোনাৰ ওচৰৰ বজাৰ বা গাঁও কোনখন?", ur: "آپ کے پاس کا بازار یا قصبہ کون سا ہے؟" } },
];

export function slotOptions(s, d) {
  if (s.key === "district_name") return DISTRICTS.map(x => [x[0], x[0]]);
  if (s.key === "education_grade") return d.edu;
  if (s.key === "preference") return d.pref;
  return null;
}

export function slotChips(s, d) {
  if (s.key === "primary_interest") return d.interest_chips;
  if (s.key === "family_occupation") return d.family_chips;
  return null;
}

export function dispOf(k, v, lang) {
  const d = DATA[lang];
  const m = {
    education_grade: (d.edu.find(e => e[0] === v) || [, v])[1],
    preference: (d.pref.find(p => p[0] === v) || [, v])[1],
    mobility_constraint: v ? D[lang].yes : D[lang].no,
    language: langName(v),
  };
  return k in m ? m[k] : v;
}
